# Generated by Django 4.0.2 on 2022-02-24 16:07

import django.core.validators
from django.db import migrations, models
import expenses_tracker.web.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('image', models.URLField()),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15, validators=[expenses_tracker.web.validators.only_letters_validator, django.core.validators.MinLengthValidator(2)])),
                ('last_name', models.CharField(max_length=30, validators=[expenses_tracker.web.validators.only_letters_validator, django.core.validators.MinLengthValidator(2)])),
                ('budget', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('image', models.ImageField(blank=True, default='profiles/', null=True, upload_to='', validators=[expenses_tracker.web.validators.MaxFileSizeInMbValidator(5)])),
            ],
        ),
    ]
