# Generated by Django 4.0.2 on 2022-02-24 16:38

import django.core.validators
from django.db import migrations, models
import expenses_tracker.web.validators


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=15, validators=[expenses_tracker.web.validators.only_letters_validator, django.core.validators.MinLengthValidator(2)], verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='profiles/', null=True, upload_to='', validators=[expenses_tracker.web.validators.MaxFileSizeInMbValidator(5)], verbose_name='Profile Image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=30, validators=[expenses_tracker.web.validators.only_letters_validator, django.core.validators.MinLengthValidator(2)], verbose_name='Last Name'),
        ),
    ]
