# Generated by Django 4.0.2 on 2022-02-24 19:12

from django.db import migrations, models
import expenses_tracker.web.validators


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_profile_first_name_alter_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='image',
            field=models.URLField(verbose_name='Link to Image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='profile/', null=True, upload_to='', validators=[expenses_tracker.web.validators.MaxFileSizeInMbValidator(5)], verbose_name='Profile Image'),
        ),
    ]
