# Generated by Django 4.0.2 on 2022-02-26 15:38

from django.db import migrations, models
import expenses_tracker.web.validators


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_expense_image_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', validators=[expenses_tracker.web.validators.MaxFileSizeInMbValidator(5)], verbose_name='Profile Image'),
        ),
    ]
